run doall:
	rm -f *.bw *.bed.gz *.bedgraph.gz
	bash run_dREG.bsh ../data/CD4_Mouse_plus.bw ../data/CD4_Mouse_minus.bw mouse_dreg /local/storage/data/dREG-Model/asvm.mammal.RData /local/storage/data/mm10/mm10.chromInfo 15
	bash run_dREG.bsh ../data/CD4_Rat_plus.bw ../data/CD4_Rat_minus.bw rat_dreg /local/storage/data/dREG-Model/asvm.mammal.RData /local/storage/data/rn6/rn6.chromInfo 15

